# Generated by Django 3.1.1 on 2020-09-25 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='seller_id',
            field=models.EmailField(max_length=254),
        ),
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
