# Generated by Django 3.1.1 on 2020-09-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_callabacks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trak_id', models.IntegerField()),
                ('orders', models.ManyToManyField(to='order.Order')),
            ],
        ),
    ]
