# Generated by Django 3.1.1 on 2020-09-25 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_trak'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='trak_id',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Trak',
        ),
    ]
