# Generated by Django 3.1.1 on 2020-09-25 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20200925_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tag',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.CreateModel(
            name='OrderTrak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bk_transaction', models.CharField(max_length=90)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
        ),
    ]
